# -*- coding: utf-8 -*-
"""Trabajo_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17mnRAY48nX6puh34LU3MuJPetptbcTyr
"""

import pandas as pd
import pandas.io.formats.excel
import os
import numpy as np
import altair as alt

os.getcwd()

siaf1 = pd.read_excel("siaf_2020.xlsx")
siaf2 = pd.read_excel("siaf_2021.xlsx")

"""#***Analizar la tasa de ejecución del Gasto Público***


Los presentes graficos serviran para analizar cual es la tasa de ejecución de inversiones de los distintos departamentos del Perú.
Para la siguiente presentacion, se analizaran tres tipos de indicadores. Estos son los siguientes:


a) Devengado / PIM


b) Devengado/PIA


c) Devengado / PIA + Saldo de Balance

Nota: 
PiM              -> Presupuesto Institucional Modificado

PIA              -> El Presupuesto Institucional de Apertura

Saldo de Balance -> PIM - Devengado del año anterior

Devengado        -> Monto ejecutado en inversiones

Es necesario calcular el Saldo de Balance para tener un mejor analisis de los indicadores de tasa de ejecucion de inversiones. El saldo de Balance nos permite conocer cuanto es el dinero no ejecutado del año anterior al evaluado que deber ser sumada a la PIA actual, ya que la suma de estos 2 numeros es el monto conocido por cada Departamento a inicios de año para distribuir entre sus proyectos de inversión.
"""

siaf2['Saldo Balance']=siaf2['PIM']-siaf2['Devengado']
siaf2=siaf2.drop(['PIA','PIM','Certificacion','Compromiso Anual','Devengado','Girado','Avance'],axis=1)
siaf2

siaf=pd.merge(siaf1,siaf2,
             on= "Departamento",
             how = "inner",
             )
siaf

"""#***Construyendo los indicadores***"""

siaf['D_PIM']=siaf['Devengado']/siaf['PIM']
siaf['D_PIA']=siaf['Devengado']/siaf['PIA']
siaf['D_PIA_SB']=siaf['Devengado']/(siaf['PIM']+siaf['Saldo Balance'])
siaf

base=siaf.filter(["Departamento","D_PIM","D_PIA","D_PIA_SB"])
base

base.insert(1, "Numeros", [30, 10, 20, 11, 21, 22, 12, 23, 24, 25, 13, 26, 14, 15, 16, 31,32, 17,27, 18, 28, 33, 19, 9,34])
base

conditionlist = [
    (base['Numeros'] >= 30) ,
    (base['Numeros'] > 19) & (base['Numeros'] <= 29),
    (base['Numeros'] <= 19)]
choicelist = ['Selva', 'Sierra', 'Costa']
base['Region'] = np.select(conditionlist, choicelist, default='Not Specified')
base

"""#***Analisis de Gráficos***

## ***1er Indicador***

**Devengado/PIM**

Este indicador nos muestra cual es la tasa de ejecución de inversiones de los distintos departamentos del Perú. Es decir, que porcentaje del presupuesto modificado en el 2021 ha sido utilizado por las autoridades de cada departamento. Este indicador esta bien que este entre esos valores, ya que considerando que es el presupuesto modificado, los departamentos pueden haber recibio dinero en los ultimos meses del año que dificulta adecuarlo correctamente en el resto del año. Esta diferencia quedara para el siguiente año.
"""

alt.Chart(base).mark_bar().encode(
    x = alt.X("Departamento",title = "Departamentos del Perú"),
    y = alt.Y("D_PIM",title = "Tasa de Ejecución de Inversiones"),
    color = "Region"
    ).interactive().properties(
    title={
      "text": ["Tasa de Ejecución de Inversiones de los Departamentos del Perú en el 2021"], 
      "subtitle": ["Indicador : (Devengado/PIM)",
                   "Fuente: SIAF Consulta amigable del MEF"],
      "color": "Black",
      "subtitleColor": "blue"
    })

"""## ***2do Indicador***

**Devengado/PIA**

Este indicador nos muestra cual es la tasa de ejecución de inversiones de los distintos departamentos del Perú. Es decir, que porcentaje del presupuesto inicial en el 2021 ha sido utilizado por las autoridades de cada departamento. Este indicador esta bien que este entre esos valores, ya que considerando que es el presupuesto inicial, los departamentos han ejecutado como minimo su presupuesto conocido a incios del año. Que este indicador sea mayor que uno indica que se ha ejecutado mas de lo que se conocia a principios de año, y esto es logico teniendo en cuenta que a veces aumenta el presupuesto despues del inicio del año (no es que solo tendran el presupuesto de inicio de año, en lo que resta de este también pueden haber recibido dinero). 
"""

alt.Chart(base).mark_bar().encode(
    x = alt.X("Departamento",title = "Departamentos del Perú"),
    y = alt.Y("D_PIA",title = "Tasa de Ejecución de Inversiones"),
    color = "Region"
    ).interactive().properties(
    title={
      "text": ["Tasa de Ejecución de Inversiones de los Departamentos del Perú en el 2021"], 
      "subtitle": ["Indicador : (Devengado/PIA)",
                   "Fuente: SIAF Consulta amigable del MEF"],
      "color": "Black",
      "subtitleColor": "blue"
    })

"""## ***3er Indicador***

**Devengado/ (PIA + Saldo de Balance)**

Este indicador es el mejor para medir cual es la verdadera tasa de ejecucion de los departamentos y esto es principalmente por dos razones. La primera de ellas es que el primero considera al PIM y este al ser el modificado, a veces las autoridades no pueden usar dinero recibido en octubre, por ejemplo, porque para invertir se requiere planes de inversión y esto muchas veces toma tiempo. En segundo lugar, el PIA es el otro extremo este indicador es poco estricto porque considera como presupuesto solo al inicial, sin embargo en muchos casos, queda dinero del año anterior que no se utilizo. Por ello, este indicador considera este caso y suma como comparacion a la PIA el dinero que quedo del año pasado, es decir el saldo de balance.






"""

alt.Chart(base).mark_bar().encode(
    x = alt.X("Departamento",title = "Departamentos del Perú"),
    y = alt.Y("D_PIA_SB",title = "Tasa de Ejecución de Inversiones"),
    color = "Region"
    ).interactive().properties(
    title={
      "text": ["Tasa de Ejecución de Inversiones de los Departamentos del Perú en el 2021"], 
      "subtitle": ["Indicador : (Devengado/ (PIA + Saldo de Balance)",
                   "Fuente: SIAF Consulta amigable del MEF"],
      "color": "Black",
      "subtitleColor": "blue"
    })